import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-student',
  templateUrl: './student.component.html',
  styleUrls: ['./student.component.scss']
})
export class StudentComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  formData=[
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
    {
      firstName:'bhalani',
      lastName:'tirth',
      age:'21',
      contact:'9510544008',
      company:'Realloc',
    },
  ]
}
